blog/home/views.py
from functools import wraps
from flask import Blueprint, render_template, g, url_for, abort,request, Response
from ..models.article import Article
from ..models.category import Category
from ..models.tag import Tag
from ..models.archive import Archive
from ..helpers import CacheFile,find_dict_in_list,pages
home = Blueprint('home', __name__, template_folder='templates',static_folder='static', static_url_path='/home/static')

def article_page(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        g.article_num = Article.count()
        g.limit = ((g.page - 1) * g.per_page, g.per_page)
        return f(*args, **kwargs)
    return decorated_function

@home.route('/')
@article_page
def index():
    archives = Archive.findAll()
    articles = Article.findAll(None,orderBy='addtime DESC',limit=g.limit)
    page_list = pages(g.page, g.article_num, g.per_page,  url_for('home.index'))
    return render_template('home/index.html',
                            articles=articles,
                            categorys=g.categorys,
                            tags=g.tags,
                            archives=archives,
                            page_name='home',
                            page_list=page_list)

@home.route('/category')
def category():
    return render_template('home/cloud.html', categorys=g.categorys, page_name='category')

@home.route('/category/<category_id>')
@article_page
def index_category(category_id):
    archives = Archive.findAll()
    category = find_dict_in_list(g.categorys, 'id', category_id)
    if not category:
        abort(404)
    articles = Article.findAll('category=?',[category_id],limit=g.limit)
    page_list = pages(g.page, g.article_num, g.per_page,  url_for('home.index_category', category_id=category_id))
    return render_template('home/index.html',
                            articles=articles,
                            categorys=g.categorys,
                            category_id=category_id,
                            tags=g.tags,
                            archives=archives,
                            page_list=page_list)

@home.route('/tag')
def tag():
    return render_template('home/cloud.html', tags=g.tags, page_name='tag')

@home.route('/tag/<tag_id>')
@article_page
def index_tag(tag_id):
    archives = Archive.findAll()
    tag = find_dict_in_list(g.tags, 'id', tag_id)
    if not tag:
        abort(404)
    articles = Article.findAllByTag(tag_id, limit=g.limit)
    page_list = pages(g.page, g.article_num, g.per_page,  url_for('home.index_tag', tag_id=tag_id))
    return render_template('home/index.html', 
                            articles=articles,
                            categorys=g.categorys, 
                            tag_id=tag_id,
                            tags=g.tags,
                            archives=archives,
                            page_list=page_list)

@home.route('/archive')
def archive():
    archives = Archive.findAll()
    return render_template('home/cloud.html', archives=archives)

@home.route('/archive/<month>')
@article_page
def index_archive(month):
    archives = Archive.findAll()
    archive = find_dict_in_list(archives, 'month', month)
    if not archive:
        abort(404)
    articles = Article.findAll('archive=?', [month], limit=g.limit)
    page_list = pages(g.page, g.article_num, g.per_page,  url_for('home.index_archive', month=month))
    return render_template('home/index.html', 
                            articles=articles,
                            categorys=g.categorys,
                            month=month,
                            tags=g.tags,
                            archives=archives,
                            page_list=page_list)

@home.route('/article/<article_id>')
def article(article_id):
    article = Article.findOne('id=?', [article_id])
    if not article :
        abort(404)

    article['tags'] = article['tags'].split(',')
    return render_template('home/article.html', article=article, categorys=g.categorys, tags=g.tags)

@home.route('/article/<article_id>/raw')
def article_raw(article_id):
    article = Article.findOne('id=?', [article_id])
    if not article :
        abort(404)
    return Response('##'+article['title']+'\n\n'+article['content'], content_type='text/plain; charset=utf-8')

@home.route('/search/<keyword>')
def search(keyword):
    if not keyword:
         redirect(url_for('home.index'))
    articles = Article.findAll('title LIKE ?', ['%'+keyword+'%'])
    return render_template('home/index.html', articles=articles,keyword=keyword, categorys=g.categorys, tags=g.tags)

@home.route('/test')
def test():
    Tag.cache()
    Category.cache()
    return 'ok'

blog/home/templates/home/article.html
{% extends "home/page.html" %}
{% block style %}
<link href="{{ url_for('home.static', filename='css/code.css') }}" rel="stylesheet">
{% endblock %}

{% set dict_categorys = categorys|list_to_dict %}
{% set dict_tags = tags|list_to_dict %}

{% block content %}
<div class="article">
    <header>
        <h1 class="title">{{ article.title }}</h1>
        <div class="text-muted font-kai">
            <span>
                发表日期：<span>{{ article.addtime|datetimeformat }}</span>
            </span>
            <span>
                &nbsp;&nbsp;|&nbsp;&nbsp;类别：<a href="{{url_for('home.index_category', category_id=article.category)}}" class="u-link-default">{{ dict_categorys[article.category|string].name }}</a>
            </span>
            <span>
                {% if article.tags %}
                &nbsp;&nbsp;|&nbsp;&nbsp;标签：
                {% for tag_id in article.tags %}
                {% if loop.index > 1%},{% endif %}
                <a href="{{url_for('home.index_tag', tag_id=tag_id)}}" class="u-link-default">{{ dict_tags[tag_id].name }}</a>
                {% endfor %}
                {% endif %}
            </span>
            <span>
                &nbsp;&nbsp;|&nbsp;&nbsp;<a target="_blank" href="{{url_for('home.article_raw', article_id=article.id)}}">查看源文件</a>
            </span>
        </div>
    </header>
    <div class="content">
        {% autoescape false %}
        {{ article.content_html}}
        {% endautoescape %}
    </div>
</div>
{% endblock %}

{% block rightside %}
    <div class="toc hidden-sm-down">
        <div class="doc doc-toc"></div>
        {% autoescape false %}
            {{ article.toc_html }}
        {% endautoescape %}
    </div>
{% endblock %}

blog/home/templates/home/cloud.html
{% extends "home/layout.html" %}
{% block container %}
<ul class="breadcrumb mt-4">
    <li class="breadcrumb-item"><a href="{{ url_for('home.index') }}">首页</a></li>
    <li class="breadcrumb-item"><a href="">{% if tags is defined %}标签{% elif categorys is defined%}类别{% elif archives is defined%}归档{% endif %}</a></li>
</ul>
<div class="cloud pt-3" style="width:60%;margin:auto">
    {% if tags %}
        {% for tag in tags %}
        <a href="{{ url_for('home.index_tag', tag_id=tag.id) }}" rel="{{ tag.num }}">{{ tag.name }}</a>
        {% endfor %}
    {% elif categorys %}
        {% for category in categorys %}
        <a href="{{ url_for('home.index_category', category_id=category.id) }}" rel="{{ category.num }}">{{ category.name }}</a>
        {% endfor %}
    {% elif archives %}
        {% for archive in archives %}
        <a href="{{ url_for('home.index_archive', month=archive.month) }}" rel="{{ archive.num }}">{{ archive.month }}</a>
        {% endfor %}
    {% endif %}
</div>
{% endblock %}

{% block script %}
{% endblock %}

blog/home/templates/home/index.html
{% extends "home/page.html" %}
{% set dict_categorys = categorys|list_to_dict %}
{% set dict_tags = tags|list_to_dict %}
{% block breadcrumb %}
{% if category_id %}
<ul class="breadcrumb">
    <li class="breadcrumb-item active"><a class="u-link-animate"href="{{ url_for('home.index') }}">首页</a></li>
    <li class="breadcrumb-item"><a href="{{ url_for('home.category') }}">类别</a></li>
    <li class="breadcrumb-item"><a href="">{{ dict_categorys[category_id].name }}</a></li>
</ul>
{% elif tag_id %}
<ul class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{ url_for('home.index') }}">首页</a></li>
    <li class="breadcrumb-item"><a href="{{ url_for('home.tag') }}">标签</a></li>
    <li class="breadcrumb-item"><a href="">{{ dict_tags[tag_id].name }}</a></li>
</ul>
{% elif month %}
<ul class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{ url_for('home.index') }}">首页</a></li>
    <li class="breadcrumb-item"><a href="{{ url_for('home.archive') }}">归档</a></li>
    <li class="breadcrumb-item"><a href="">{{ month }}</a></li>
</ul>
{% elif keyword %}
<ul class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{ url_for('home.index') }}">首页</a></li>
    <li class="breadcrumb-item"><a href="">搜索：{{ keyword }}</a></li>
</ul>
{% endif %}
{% endblock %}

{% block rightside %}
<div class="card">
    <div class="card-header px-2 py-1 "> 分类</div>
    <div class="card-block px-3 py-2">
    {% for c in categorys %}
     <a href="{{ url_for('home.index_category', category_id=c.id) }}" class="font-size-sm pr-1 {% if c.id|string == category_id %}active{% endif %}"> {{ c.name }} {% if c.num > 0 %}<sup>{{ c.num }}</sup>{% endif %}</a>
    {% endfor %}
    </div>
</div>
<div class="card mt-4">
    <div class="card-header px-2 py-1">标签 </div>
    <div class="card-block px-3 py-2">
        {% for t in tags %}
        <a href="{{ url_for('home.index_tag', tag_id=t.id) }}" class="font-size-sm pr-1 {% if t.id|string == tag_id %}active{% endif %}"> {{ t.name }} {% if t.num > 0 %}<sup>{{ t.num }}</sup>{% endif %}</a>
        {% endfor %}
    </div>
</div>
<div class="card mt-4">
    <div class="card-header px-2 py-1">归档</div>
    <ul class="list-group list-group-flush">
    {% for a in archives %}
    <li class="list-group-item px-3 py-2  {% if loop.index == 1%}border-top-0{% endif %}"><a href=" {{ url_for('home.index_archive', month=a.month) }}" class="font-size-sm {% if a.month == month %}active{% endif %}"> {{ a.month|num_to_date }} {% if a.num > 0 %}<sup>{{ a.num }}</sup>{% endif %}</a></li>
    {% endfor %}
    </ul>
</div>
<div class="card mt-4 mb-4">
    <div class="card-header px-2 py-1">链接 </div>
    <div class="card-block px-3 py-2">
    </div>
</div>
{% endblock %}

{% block content %}
    <ul class="list-group">
        {% for article in articles %}
        <li class="list-group-item list-group-item-action justify-content-between">
            <span>
                <a href="{{ url_for('home.article', article_id=article.id) }}" class="font-weight-bold">{{ article.title }}</a>
            </span>
            <span>
                <a href="{{ url_for('home.index_category', category_id=article.category) }}" class="font-size-sm">#{{ dict_categorys[article.category|string].name }}</a> · <span class="text-muted font-size-sm">{{ article.addtime|datetimeformat }}</span>
            </span>
        </li>
        {% else %}
        没有文章！
        {% endfor %}
    </ul>
    {% autoescape false %}
        {{ page_list }}
    {% endautoescape %}
 {% endblock %}

blog/home/templates/home/layout.html
<!DOCTYPE html>
<head lang="en">
    <title>{{ title|default('flask-blog')}}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="//cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    {% block style %}{% endblock %}
    <link href="{{ url_for('home.static', filename='css/main.css') }}" rel="stylesheet">
    <link rel="shortcut icon" href="{{ url_for('home.static', filename='favicon.ico') }}">
</head>
<body>
    <header class="navbar navbar-toggleable-md navbar-inverse bg-primary">
        <nav class="container">
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#yf-main-nav" aria-controls="yf-main-nav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('home.index') }}">flask-blog</a>
            <div class="collapse navbar-collapse" id="yf-main-nav">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item {% if page_name == 'home' %}active{% endif %}">
                        <a  class="nav-link" href="{{ url_for('home.index') }}"> 首页</a>
                    </li>
                    <li class="nav-item {% if page_name == 'category' %}active{% endif %}">
                        <a  class="nav-link" href="{{ url_for('home.category') }}"> 类别</a>
                    </li>
                    <li class="nav-item {% if page_name == 'tag' %}active{% endif %}">
                        <a  class="nav-link" href="{{ url_for('home.tag') }}"> 标签</a>
                    </li>
                </ul>
                <form action="/search" id="search-form" class="form-inline" onsubmit="return false">
                    <input class="form-control mr-sm-2" type="text" id="search-keyword" {% if keyword %}value="{{keyword}}"{% endif %} placeholder="搜索一下，你就知道...">
                    <button class="btn btn-info my-2 my-sm-0" id="search-btn">搜索</button>
                </form>
            </div>
        </nav>
    </header>
    <div class="container">
        {% block container %}{% endblock %}
        <div class="uk-animation-toggle">
            <a href="#" class="gotop uk-visible@m uk-animation-shake" uk-totop></a>
        </div>
    </div>
    <footer>
    </footer>
</body>
<script src="//cdn.bootcss.com/jquery/3.1.1/jquery.min.js"></script>
<script src="{{ url_for('home.static', filename='js/main.min.js') }}"></script>
{% block script %}{% endblock %}
</html>

blog/home/templates/home/page.html
{% extends "home/layout.html" %}
{% block container %}
<div class="row pt-4">
    <div class="col-12 col-md-3 push-md-9 ">
        {% block rightside %}{% endblock %}
    </div>
    <div class="col-12 col-md-9 pull-md-3 ">
        {% block breadcrumb %}{% endblock %}
        {% block content %}{% endblock %}
    </div>
</div>
{% endblock %}